### ISSUE TITLE
`Q` Upgrade policy, what has been patched, .. 

### ISSUE THREAD

**Issue by MangoIV** [privatevoid-net/nix-super#8]
Hi, I would like to ask whether this is going to be updated regularly. I'd really like to use it but I fear that this will just fall behind...

Additionally I would like to ask, whether it's possible to not have this as a fork but rather as a curated patchset so it's easier to see what is actually changed without grepping through the history. 

Thanks in advance and thank you for making this.

**Comment by max-privatevoid** [comment]
The current update policy is "I'll merge nixos/master every once in a while or if there's a shiny new feature upstream that I want to use". It might be a good idea to automate this with Hercules CI scheduled effects. Weekly updates sounds good, I think. 
Relevant to current state: Upstream seems to be broken on master currently (https://github.com/NixOS/nix/pull/7856), so I'll hold off on updates for a bit until that situation gets resolved.

The original version of this project was a curated patchset (https://git.privatevoid.net/max/nix-super-archived). I switched away from that model because fixing patch conflicts after updating the upstream rev was a tedious task. Taking advantage of Git's conflict resolution capabilities makes this a nicer experience. I'd be okay with changing it back to the patchset style if you know a decent workflow for it. Having a place where all the changes in this fork are documented could be a decent solution to your problem as well.

**Comment by MangoIV** [comment]
> I switched away from that model because fixing patch conflicts after updating the upstream rev was a tedious task

that makes sense, thank you for clarifying 

> "I'll merge nixos/master every once in a while or if there's a shiny new feature upstream that I want to use"

haha, okay, I'll roll with this >3

Thank you for making this!
